### ISSUE TITLE
几个功能建议

### ISSUE THREAD

**Issue by Pau1am** [JOZA-ORANGE/MCDR-joinMOTDnext#1]
1.目前服务器新老玩家加入服务器都使用同一个MOTD，能否为新玩家加入设立一个新的MOTD配置选项？
2.能否在MOTD中加入随机文本？即在预先写入的多条内容中随机发出其中一条。
3.能否添加message标签，使玩家透过点击文本转移到其他子服务器？

**Comment by JOZA-ORANGE** [comment]
第一条：我会尽量尝试实现
第二条：我会在下个版本中实现
第三条：不知道你是不是使用类似于/server  <server_name>的指令来跳转到子服，如果是，你可以尝试使用cmd或者fill来实现
最后，感谢你的提议☺️

**Comment by Pau1am** [comment]
感谢大佬awa
