### ISSUE TITLE
示例中执行指令方法在实装后无法使用

### ISSUE THREAD

**Issue by JiangShi-GitHub** [JOZA-ORANGE/MCDR-joinMOTDnext#4]
实装后在游戏中点击没有反应
config书写如下
![屏幕截图 2023-10-30 171434](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/assets/87858199/9fc088be-fa00-4b85-b29c-2726f98df843)

**Comment by JOZA-ORANGE** [comment]
这样写应该是不行的
可以换成fill，这样的话可以填充到消息框里，但是需要手动回车发送
我示例里面有误，稍后会改掉

**Comment by JiangShi-GitHub** [comment]
1.20.1



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月30日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [JOZA-ORANGE/MCDR-joinMOTDnext] 示例中执行指令方法在实装后无法使用 (Issue #4) |

请问游戏版本是？

**Comment by JOZA-ORANGE** [comment]
你可以尝试一下(v=op {player})，时间太久了，我也忘记怎么写的了

**Comment by JiangShi-GitHub** [comment]
也不行，不过text是正常的
![屏幕截图 2023-10-30 184041](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/assets/87858199/f8b37251-4af3-41a5-8bd3-c46e74c9a60d)

**Comment by JOZA-ORANGE** [comment]
> 也不行，不过text是正常的
> ![屏幕截图 2023-10-30 184041](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/assets/87858199/f8b37251-4af3-41a5-8bd3-c46e74c9a60d)
> 

仔细想了一下，我刚才犯了个小错误，那样子确实是不行，
要想实现你的那个获取op的功能，可以用cmd标签，然后v=!!op
但是考虑到你是1.20.1，客户端需要安装相应的模组：[LetMeClickAndSend](https://github.com/Fallen-Breath/LetMeClickAndSend/releases)
